### ISSUE TITLE
Arduino Uno  (COMx)  not USB Serial Port (COMx) 

### ISSUE THREAD

**Issue by neo11ro** [carm87/Arduino-Busmaster#1]
I was trying to use this with Arduino Uno I set all as in the description.
I think the issue is that COM port is shown as Arduino Uno  (COMx), not as USB Serial Port (COMx) .
I've tried to find a Windows option where I can change the name but did not manage to.
Is there a way to change it in the Arduino project to look for Arduino Uno ?

**Comment by neo11ro** [comment]
Manage to change the Port Name in Windows following this instructions

1. Open Device Manager
2. Browse to the COM Port or device you're interested in changing
3. ight click the device and select "Properties"
4. Select the "Details" tab
5. In the "Property" box, select "Container ID"
6. Copy the "Value" presented
7. Open the Registry editor a. MUST now back up the registry in case you boff something and need a road home.
8. Select the "Edit" menu once your registry is loaded
9. Select "Find" a. insert the copied value into the "Find What?" box. b. select the "Find Next" button. c. You may have to select "Find Next" several times until you find the registry entry you're looking for. You'll know you have the correct registry entry when you come across one that contains the REG_SZ value Name of "Friendly Name."
10. Double-click the "Friendly Name" icon. This will open an editable box for you to change the name of the item. In my case, when I change the friendly name of a COM port I only change the name and not the COM port number. This does have the potential to get gummed up if you aren't careful with what you do.
11. After you make your change, exit the registry editor and reboot.
12. Open the Device Manager and you should see that device's friendly name changed to what you desired. Hope this helps...

Now the issue is that when I click on Search for device BusMaster stops responding.
<img width="236" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/39a00771-1523-45ca-8a12-ff34fb351ae6">

**Comment by carm87** [comment]
Hello Neo,
Send me a couple of screenshot of busmater.
Have you used patched vscom DLL?

**Comment by carm87** [comment]
And also you could try opening com port with other software (e.g.) putty and check if It responsive

**Comment by neo11ro** [comment]
> Hello Neo, Send me a couple of screenshot of busmater. Have you used patched vscom DLL?

I've added the .dll file, I've try also with other builds of Busmaster, same result when I click on search it freezes.

<img width="1295" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/448c60f1-dfbe-413a-8bb2-7863b6537c3f">
<img width="294" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/439c368b-6748-4281-9a8f-3952022b2890">

**Comment by neo11ro** [comment]
> And also you could try opening com port with other software (e.g.) putty and check if It responsive

<img width="645" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/f62fd487-460e-4604-95ea-831c4d169a68">

<img width="500" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/c27913f9-3b8d-43e3-a944-9de40ac62029">
It looks like speed is not ok or other issue.
I've loaded the program without any issues.
<img width="1276" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/b8b83fba-c60a-4b0a-aa55-f754288e3a9b">
I've tried Arduino with other sketchs and work OK, I have Arduino UNO R3

**Comment by carm87** [comment]
this is how appear to me:
i'm using patched dll and arduino uno clone (with chip CH340).

![image](https://github.com/carm87/Arduino-Busmaster/assets/47579066/5e43d3b7-fbe1-4bc5-971f-f48076d58189)

this is connection with putty

![image](https://github.com/carm87/Arduino-Busmaster/assets/47579066/f46ad12a-5109-49fb-a720-64cf3ab525b2)

no echo should appear in it and typing v + enter you should receive this

![image](https://github.com/carm87/Arduino-Busmaster/assets/47579066/080ad5ee-4e12-44f9-a927-fdd0d9c58036)

I would suggest to install again serial port driver until it works with putty and then test it with busmaster

**Comment by neo11ro** [comment]
Thank you for the help.
Do not think is the serial as I can flash another sketch and the serial works fine. This is a 2.4GHz scanner as you can see all works ok on serial.
<img width="1271" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/6086c82a-fc80-4777-917c-316c1747bc39">
I've also renamed my serial as you have it still nothing.
<img width="254" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/50ace399-a5d8-4036-b5aa-0d90ee5a536e">
Will play with the speeds and settings and maybe will get it to work. 
Maybe I have a different Arduino chip "Arduino uno atmega328p"

**Comment by neo11ro** [comment]
Should it detect it without the CAN shield ?
Just thought the issue might come from the CAN shield, I've tried without it also, and same result.
Also, would it matter  Arduino SW version, did you try to compile with the latest version ?
<img width="275" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/8e21d39b-7b1e-4c06-9b11-19bf09701a71">

**Comment by carm87** [comment]
Should it detect it without the CAN shield ?
yes it should - detection means it send V and see the version as response more or less.
Just thought the issue might come from the CAN shield, I've tried without it also, and same result.
Also, would it matter Arduino SW version, did you try to compile with the latest version ?
i didn't use last version for sure. i will soon do an update in git to support a display. maybe for this I can provide also the HEX/BIN.

**Comment by carm87** [comment]
![IMG_20240212_195044636_HDR](https://github.com/carm87/Arduino-Busmaster/assets/47579066/20ffbc1e-4793-4934-b833-b194a95e2f7d)

**Comment by neo11ro** [comment]
> ![IMG_20240212_195044636_HDR](https://github.com/carm87/Arduino-Busmaster/assets/47579066/20ffbc1e-4793-4934-b833-b194a95e2f7d)
> 

That looks really good. Nice one!@

**Comment by carm87** [comment]
just published

**Comment by neo11ro** [comment]
So manage to flash your build and looks OK.
So I think there is an issue with the new Arduino SW version, you might try to see if it will work for you.
I've used ACRDUDESS to flash the hex file 
<img width="484" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/b7a217cb-fd88-4076-aed2-3f754fe1965d">
In case anyone else faces the same issue. 
I think this thread  can be close.

**Comment by carm87** [comment]
Good to know. May you please confim you also tried to build updated source and It does not work.

**Comment by neo11ro** [comment]
> Good to know. May you please confim you also tried to build updated source and It does not work.

Yes, that also works. The only issue remaining BusMaster is not able to scan COM ports under Windows 11, I've tried on a Windows XP, and works fine.
With the original dll on Windows 11 it also freezes, so maybe is a VSCom issue not being compatible with Windows 11, or maybe it interferes with other stuff I have install.

**Comment by neo11ro** [comment]
I've also try adding the latest vscom api from their website. BusMaster still freezes, it says is compatible with windows 10, so still not sure if is the api or BusMaster.
<img width="241" alt="image" src="https://github.com/carm87/Arduino-Busmaster/assets/3754696/2ee4cf2d-2864-4565-ab3f-fd8d3f36afa7">

**Comment by carm87** [comment]
ok I never used on 11 only 10 or 7.
